services:
    web:
        container_name: web
        build:
            context: ./web
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./web:/code/web
        ports:
            - "${WEB_PORT}:3000"
        environment:
            ENV_MODE: ${ENV_MODE}
        restart: always
