services:
    web:
        container_name: web
        build:
            context: ./web
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./web:/code/web
            - ./shared:/code/shared
        ports:
            - "${WEB_PORT}:3000"
        environment:
            ENV_MODE: ${ENV_MODE}
        depends_on:
            - database
        restart: always

    monitoring:
        container_name: monitoring
        build:
            dockerfile: ./monitoring/docker/Dockerfile
        volumes:
            - ./monitoring:/code/monitoring
            - ./shared:/code/shared
        environment:
            ENV_MODE: ${ENV_MODE}
        depends_on:
            - database
        restart: always

    shared:
        container_name: shared
        build:
            dockerfile: ./shared/docker/Dockerfile
        volumes:
          - ./shared:/code/shared

    database:
        image: mariadb
        container_name: database
        ports:
            - "${MARIADB_PORT}:3306"
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        volumes:
            - "database-data:/var/lib/mysql"
        restart: always

    adminer:
        image: adminer
        ports:
            - "81:8080"
        depends_on:
            - database

volumes:
    database-data:
